### ISSUE TITLE
Working on the Apache proposal draft

### ISSUE THREAD

**Issue by wu-sheng** [OpenSkywalking/Organization#10]
This is the discussion place about Apache incubator proposal. Apache member @michaelsembwever will help me to do this. I will drop the proposal in this [wiki page](https://github.com/OpenSkywalking/Organization/wiki/Skywalking-Apache-Proposal-Draft). 

All members of @OpenSkywalking/pmc @OpenSkywalking/committer-team @OpenSkywalking/huawei-devcloud-contributor-team can give me feedbacks through any channel you like, e.g GitHub comments, Gitter, Wechat, Cell Phone, Huawei internal espace.

@michaelsembwever , we can stay in gitter, or discuss in here. And you have the right to edit the `proposal`.

**Comment by hanahmily** [comment]
🎉🎉 🎉  Thanks for creating this proposal. This is a very big step forward for the `SkyWalking` project and encourages everyone to move on. 💪 💪 💪

**Comment by michaelsembwever** [comment]
Thanks @wu-sheng 
I'm here and very happy to help. I believe we are in similar time zones, which will make things a lot easier. So anyone who's got any questions please do reach out 😎

**Comment by wu-sheng** [comment]
I finished the first edition. Please review it.

**Comment by wu-sheng** [comment]
@bsideup Received your notification, and do the adjustments. Also I invited you to join the project as a collaborator. So you can help us out in the Apache way.

**Comment by peng-yongsheng** [comment]
This year's efforts were not in vain.

**Comment by ascrutae** [comment]
Great to hear this news. Thanks very much. @michaelsembwever

**Comment by wu-sheng** [comment]
FYI @peng-yongsheng
@ascrutae
@hanahmily
@lytscu
@zhangkewei
@oracle219
@IluckySi
@titsquid
@bai-yang

Most works have been done. @michaelsembwever will start the formal processes for us in these days.

**Comment by wu-sheng** [comment]
Mick has moved the draft proposal has been moved to https://wiki.apache.org/incubator/SkyWalkingProposal . We will work on that, and post our formal proposal soon.
