### ISSUE TITLE
[Vote] Donate Skywalking to Apache Foundation

### ISSUE THREAD

**Issue by wu-sheng** [OpenSkywalking/Organization#11]
After several days discussion with some Apache members, the draft is almost ready: https://github.com/OpenSkywalking/Organization/wiki/Skywalking-Apache-Proposal-Draft , please vote for donating the skywalking and skywalking-ui to Apache Foundation.

The vote is for **All Initial Committers**:
* @wu-sheng
* @peng-yongsheng
* @ascrutae
* @hanahmily
* @lytscu
* @zhangkewei
* @oracle219
* @IluckySi
* @titsquid
* @bai-yang 

_Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain"._

cc @michaelsembwever

**Comment by ascrutae** [comment]
+1

**Comment by IluckySi** [comment]
+1

**Comment by hanahmily** [comment]
+1 👍

**Comment by oracle219** [comment]
+1

**Comment by wu-sheng** [comment]
+1

**Comment by bai-yang** [comment]
+1

**Comment by peng-yongsheng** [comment]
+1

**Comment by lytscu** [comment]
+1

**Comment by zhangkewei** [comment]
+1

**Comment by titsquid** [comment]
+1

**Comment by michaelsembwever** [comment]
Thanks everyone! Having these types of commitment and agreement out in the public, clear and concise, makes it a lot easier to be definite in stating community wishes and direction :-)

If anyone has any questions about the Apache Software Foundation, or the Incubation process, please reach out and ask any and all questions you may have. This can be in public or in confidence ( mck@apache.org ).

**Comment by wu-sheng** [comment]
Vote passed.

___
Skywalking PMC.
