### ISSUE TITLE
[Vote] Put 'Michael Semb Wever' as Skywalking Apache Incubator Champion

### ISSUE THREAD

**Issue by wu-sheng** [OpenSkywalking/Organization#12]
Apache member @michaelsembwever helps OpenSkywalking a lot in our way to Apache Foundation. And he is an expert of tracing(join OpenTracing before I did) and big data(Cassandra),  as we all known, there two parts are very important for APM of distributed system.

So I propose to put `Michael Semb Wever` as our Champion. 

The vote is for **All Initial Committers**:
* @wu-sheng
* @peng-yongsheng
* @ascrutae
* @hanahmily
* @lytscu
* @zhangkewei
* @oracle219
* @IluckySi
* @titsquid
* @bai-yang 

_Voters can either respond "agree, yes, +1", "disagree, no, -1", or "abstain"._

cc @michaelsembwever

**Comment by ascrutae** [comment]
+1

**Comment by zhangkewei** [comment]
+1

**Comment by oracle219** [comment]
+1

**Comment by IluckySi** [comment]
+1

**Comment by titsquid** [comment]
+1

**Comment by lytscu** [comment]
+1

**Comment by peng-yongsheng** [comment]
+1

**Comment by wu-sheng** [comment]
+1

**Comment by bai-yang** [comment]
+1

**Comment by hanahmily** [comment]
+1

**Comment by wu-sheng** [comment]
Vote passed.

___
Skywalking PMC.
