### ISSUE TITLE
[DISCUSSION] Accept yang-xiaodong join OpenSkyWalking

### ISSUE THREAD

**Issue by liuhaoyang** [OpenSkywalking/Organization#15]
Since the [skywalking-netcore project](https://github.com/OpenSkywalking/skywalking-netcore) was created, [Yang-Xiaodong](https://github.com/yang-xiaodong)(Microsoft MVP) has been actively involved in the release of skywalking-netcore. He provided the EntityFrameworkCore plugin, helped me review the code and discussed the roadmap for skywalking-netcore together.
So, I propose to invite  yang-xiaodong to join OpenSkywalking to bring more feedback for .NET Community.
@wu-sheng 
@hanahmily 
@peng-yongsheng 
@ascrutae

**Comment by wu-sheng** [comment]
Consider him as an important contributor in .net agent. I totally support your suggestion. Invite him into OpenSkywalking as a new committer.

+1 for this

**Comment by ascrutae** [comment]
+1

**Comment by hanahmily** [comment]
+1

**Comment by wu-sheng** [comment]
72 hours passed. We got 3 +1 and no -1 or 0.
I am closing this proposal and invite him in.

**Comment by wu-sheng** [comment]
@Savorboard invitation sent. Welcome.
